### ISSUE TITLE
DM은 서로 친구여야만 주고받을 수 있는데, 더 세련된 방법이 없을까요?

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#130]
현재 BE에서는 상대가 누구라도 DM을 보낼 수 있지만, FE에서는 친구에게만 보낼 수 있습니다. 
그래서 친구 신청을 하고 DM을 보내도 상대방이 나를 친구로 등록해두지 않았으면 알림을 딱히 받을 방법이 없습니다. 
일단은 그 방식으로 만들긴 하겠지만, 추후 로직 변경이 필요한 사항인 듯합니다.
더 세련된 방법은 없을까요?

**Comment by lev-Zero** [comment]
페북처럼 하단에 dm방들이 탭형식으로 쌓이는 방법을 생각해볼수있겠습니당
