### ISSUE TITLE
chatRoomDmMe를 했을 때, 나와 상대방 사이의 채팅방이 이미 있는지 여부를 알 방법이 없습니다. 

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#136]
현재 FE에서 만들려고 하는 로직을 간략히 설명하면 다음과 같습니다. 
- (dm 창을 열 때가 아니라) friends 목록 사이드바 컴포넌트가 처음 렌더링될 때, 자신의 전체 친구 목록에 대해 createChatRoomDm을 건다. 
- 이때, 이미 둘 사이에 만들어진 방이 있다면 create하지 않고 join 한다. 

그런데 이미 둘 사이에 만들어진 방이 있는지 알 방법이 없습니다. 
물론 `yopark, fake_U1's DmChatRoom` 이라는 나름 고유한 이름이 만들어지기 때문에 이미 존재하는 방 이름이라는 에러가 뜨면 만들지 않고 그 이름으로 join 하는 임시방편도 있겠습니다만, fake_U1이 방을 먼저 만드는 경우 이름이 `fake_U1, yopark's DmChatRoom`으로 달라지기 때문에 해당 조건을 잡아낼 수 없습니다. 

따라서 chatRoomDmMe 이벤트의 chatRoomDm 프로퍼티에 참여자 유저 아이디 목록을 담아서 주시면 감사하겠습니다! 그리고 내가 만든 방이 아닌 초대당한 dm 방도 chatRoomDm에 포함되어 함께 오는지 궁금합니다.

**Comment by yoopark** [comment]
원래는 알림을 못 받을까봐 접속하자마자 다 create & join 하려고 했는데, 사실 강제로 join 되기 때문에 dm 창을 열 때 create 해도 괜찮을 것 같네요!

**Comment by toy-k** [comment]
이슈 내용 읽어봤습니다.
아래와 같은 방법으로 서버 코드를 수정하면 프론트에서 일거리가 줄어 들 것 같습니다.
혹시 어떻게 생각하시나요 ?
	
=> DB기준 서버에서 특정 chatRoomDm에 user1, user2 없으면, create->join
	=> 서버측 채팅룸 이름은 랜덤 문자열(숫자)
	=> 클라이언트에 참여 유저 정보 emit로 던짐 => 클라이언트에서 DM관련 방이름 표시

=> DB기준 서버에서 특정 chatRoomDm에 user1, user2 있으면, 그대로 둠
	=>서버 내부에서는 socket.leave(room), socket.join(room) 실행
	=> 클라이언트에서는 마치 처음 Dm create-join 한 것 처럼 사용 


서버쪽 코드 아래와 같이 수정하면 괜찮을까요 ?

	1.클라이언트에서 chatRoomDm 이벤트 요청시 서버에서는 참여자 유저 아이디 목록을 방만든사람과 초대당한사람에게 응답

**Comment by yoopark** [comment]
제가 이해한게 맞는지 확인해주세요.
1. chatRoomDmMe에 joinedUser 정보를 추가해주겠다. 
2. DM 보내기를 누를 때 방을 생성한다. (이미 방이 존재하면 join)
3. DM창을 나가더라도 leave하지 않는다. 

그렇다면 발생할 수 있는 문제가, 아예 로그아웃하고 들어온 사람은 그 사람에게 DM을 보내거나 받기 전에는 join하고 있지 않기 때문에 알림을 못 받는거 아닌가요?

**Comment by toy-k** [comment]
1. chatRoomDmMe의 응답메시지를 ChatRoomDmById 처럼 응답 메시지 정보 추가하겠습니다
2. DM 보내기를 누를때, 
     2-1. 방이 없으면 방을 생성하고, 두 유저가 join 한다 (DB, socket 둘다) 그리고 둘은 채팅한다.
     2-2. 방이 있으면, 둘은 채팅한다. (생각해봤는데 딱히 join이나 leave 할필요없는것같아요. 서버 코드가 재실행되지 않는이상 서버 입장에서는 해당 DM룸에 2명은 계속 Join된 상태로 두는건 어떨까 싶더라구요)
3.맞습니다,

최대한 간단하게 과제에서 요구하는 기능을 구현하려고 해요. 
다만 직접 코드 짜면서 하다보면 가끔 비효율적으로 코드가 짜지기도 하는데, 
아무튼 현재 Chat 소켓에 연결되지 않은 유저에게 DM 보낼수없게 서버 코드 구현되어 있어요.
누군가 로그아웃했다면, 그 사람이 속해 잇던 DM룸의 joinedDmuser 정보는 DB에서 사라지고, socket 에서도 leave돼요.아예 초기화 돼요. 
누군가 chat 소켓에 연결된 사람만 DM 받을 수 있게 짜면 코드 구현이 보다 간단해질거라 생각해요.
