### ISSUE TITLE
Admin을 주고 뺏은 뒤 chatRoomById했을 때 adminUser에서 사라지지 않는 것 같아요

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#149]
정확한 건 아닌데, 이런 현상이 발생하는 것 같아서 한번 POSTMAN으로 확인 부탁드립니다!

**Comment by toy-k** [comment]
postman에서 테스트 해본 과정과 결과는 아래와 같습니다.

user1이 방만들고, user2방참여
user1이 user2 admin만들고 -> chatRoomById -> 어드민 user2 확인됌 (user1은 항상확인됌)
user1이 user2 admin 박탈 -> chatToomById -> 어드민에서 User2제거됌(user1은 항상확인됌)

**Comment by toy-k** [comment]
![image](https://user-images.githubusercontent.com/88143547/211314084-36494cff-4ece-41e3-b574-ce07a719847c.png)
칸이 확대되지 않아서 전체 데이터 공유할 순 없지만, 빨간 네모친곳보면 adminuser에 대해서 아래쪽데이터는 배열이 열려있고, 위쪽 데이터는 1명만 어드민인 채로 배열이 닫혀있는것을 알 수 있어요

**Comment by yoopark** [comment]
https://github.com/lev-Zero/lastpong/commit/ec3e2447902037e97fcfd61e6adf1b5ab622a148

프론트 문제였네요 ㅎㅎ 죄송해요;;
