### ISSUE TITLE
FE 남은 일 정리

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#150]
## 게임과 연관 없는 영역
- [ ] DM 간헐적으로 안 보내지는 오류 -> #153 
- [x] isMuted 정보 chatRoomById에서 가져와서 `MUTE 1 MIN` `UNMUTE` 상태 연동하기
- [x] unMute가 제대로 처리되지 않는 오류 -> https://github.com/lev-Zero/lastpong/commit/1378db99821d86df0f90ba27ed47914d4fdfb58f
- [x] admin을 주고 뺏었을 때 adminUser의 정보가 잘 연동되지 않는 오류
- [x] DM 보냈지만 Popover를 열지 않은 경우 msgNum 올리는 기능 추가하기
- [x] Block 기능 단체 채팅에서, DM에서 어떻게 반응하도록 할지 논의하기
- [x] Block 기능 구현하기
- [x] 리팩토링 - cleanup 함수에 socket.off 넣기
- [ ] 리팩토링 - 컴포넌트 / 기능 쪼개기
- [ ] 리팩토링 - 상태관리 적극 활용하기
- [x] 방장만 방 설정 update 할 수 있도록 하기
- [x] admin이 admin을 강퇴할 때 등등... 채팅에서 권한 부여로 발생할 수 있는 상황들 테스트 및 처리하기
- [x]  /game/options에 아바타 넣기

## 게임과 연관 있는 영역
- [x] 게임 제작하기
- [x] /game/options에서 낮은 레이팅인 사람이 테마 고르도록 하기
- [x] /watch 방 정보 연동하기
- [x] /watch/:roomNo 실제 관전
- [x] /user/:username에 매칭기록 연동하기
- [ ] 리팩토링 - GameRoomProps -> UserProps 본래 사용하던 인터페이스로 통일
- [x] 게임 플레이 이후 rating 변화
- [x] 게임 초대 모달 창 로직 제작하기

**Comment by yoopark** [comment]
- 친구는 Block할 수 없기 때문에 Block한 유저에게 DM을 보내진 못한다. 
- Block당한 유저가 나에게 DM을 보내면 서로에게 DM이 보내지지 않는다. (당신은 Block 당했습니다라는 알림이 오게 할 수도 있으나 너무 잔혹한 방법인듯 해서...)
- Block당한 유저를 단체 채팅에서 만나는 경우는, 현재에는 일반 유저와 동일하게 취급하여 이야기를 나눌 수 있음. 어떻게 처리하는게 나을까요? @toy-k

**Comment by toy-k** [comment]
이전에 나눴던 이슈여서 block관련 기능 기억하고 있습니다.
서버쪽에서 처리해보려고 이것저것 해보는데 쉽지 않네요;

이걸 클라이언트에서 처리한다면,
이런 생각 떠오르네요


단체채팅방에 여러 유저가 있고, 유저1이 유저2를 block 한 경우

1. 만약 채팅방 내에서만 블락할 수 있다면,  
유저1이 유저2를 block하면 해당 채팅룸 내 store에 block 관계를 데이터로 저장하고, 
유저2가 메시지 보낸경우, 
store의 block관계 읽고,
유저1 에게만 메시지가 렌더링 되지 않도록 처리할 수 있을 것 같습니다.

2. 채팅방 밖에서도 block 할 수 있다고 하더라도, 1번처럼 처리할 수 있을 것 같습니다. 차이는 store 내에 유저간 block관계를 전역적으로 사용하면 어떨까 싶습니다.

쓰고나서 보니,
전역적으로 1개의 block 관계 구조만 만들면돼서 
2번이 좀 더 구현 및 유지보수가 더 간단하지 않을까 싶어요.

**Comment by yoopark** [comment]
@toy-k 넵 이미 1번 방법으로 제작 완료하였습니다.

프론트엔드끼리 얘기 나눠본 결과 친구를 추가해야 DM을 할 수 있는 현 상황에서 DM에서 차단을 한다는 행위 자체가 쓸모없다는 결론에 이르렀습니다. 그래서 같은 채팅방 안의 접속자 리스트에서 우클릭 메뉴로 Block/UnBlock을 할 수 있도록 UI를 변경하였습니다. 그래서 단체 채팅방에서 Block한 유저의 말만 걸러서 안 뜨도록 만들었습니다. (백엔드에서는 메시지가 오지만 프론트엔드에서 필터링해서 띄우지 않는 중)

**Comment by lev-Zero** [comment]
admin이 admin강퇴 못하도록 권한에 따라서 보이는 메뉴 자체가 다르게 뜨게 했습니다

**Comment by yoopark** [comment]
#193으로 이전
