### ISSUE TITLE
owner가 password를 remove 할 수도 있어야 합니다. 

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#154]
https://user-images.githubusercontent.com/61629480/211354451-9ddb4cc3-a8b8-4704-b795-6816d1d8db83.mov

서브젝트에서 다음과 같이 명시되어 있습니다.
> The channel owner can set a password required to access the channel, change it, and also **remove** it.

하지만 updatePwd 메소드로는 remove는 불가능한 것 같습니다.

이왕 이렇게 된거 그냥 createChatRoom 처럼 제목까지 바꿀 수 있게 updateChatRoom을 만들고 
```
{"chatRoomId": 12, "name": "채팅룸 1", "status": 2, "password": "1234"}//protected
{"chatRoomId": 12,  "name": "채팅룸 2", "status": 0, "password": ""}//public
```
이렇게 인자를 받아서 변경할 수 있도록 하면 어떨까요..? 
저희가 create 할 때 썼던 모달을 재사용하는 게 편할 것 같아(피그마 상 디자인도 그렇게 되어있긴 합니다) 요청드립니다. 

혹시 어려우시다면 updatePwd에 status 변경 기능만이라도 추가해주시면 감사하겠습니다.

**Comment by toy-k** [comment]
그렇군요.

채팅룸 비밀번호 remove 기능 부분에 대해서
해당 기능의 본질은 채팅룸의 status 변화 같아요.
그런점에서 현재 코드에서 해당 채팅룸의 status 및 비밀번호만 변경하는 쪽으로 기능을 개선하는게 효율적일거같아요.

채팅방 이름까지 수정하는 기능을 넣는다면,
누군가 채팅방 이름 수정하고 싶을때 파라미터로 기존비밀번호, 새 비밀번호에 해당하는 값을 넣어야되고,
방 비밀번호 수정하고 싶을때 , 채팅방 이름을 추가로 넣어야 하는 불편이 생길거같아요, 물론 코드도 늘어나구요.


참고로, 채팅방 이름을 쓰거나 비밀번호를 적을때 '특수문자나 space 금지' 프론트엔드에 주의 메시지 넣을 수 있나요 ?
가령 누군가 sql injection 시도 시 DELETE * ASDF  -> DELETE*ASDF 이런식으로 코드 만들어서 작동될수없게 되어 잇어요.
혹은 <script>서버나 디비에 영향 미칠 코드<script>  -> asdlfkjaewlfjl 이런식으로 변환되게 되어 잇어요.

**Comment by yoopark** [comment]
넵 말씀하신 내용 이해했습니다! 그런데 비밀번호에도 공백/특수문자가 불가능하게 해야 하나요? 어차피 hash로 뭉개지는거 아닌가요

**Comment by toy-k** [comment]
추가한 API에 대한 참고사항 입니다. (https://github.com/lev-Zero/lastpong/pull/156)

**Comment by yoopark** [comment]
#166 으로 해결

**Comment by yoopark** [comment]
https://github.com/lev-Zero/lastpong/commit/791fd8b18e2a1a3085f5cadcaabc41f853f8631c 에서 공백/특수문자 막는 로직 추가하였습니다
