### ISSUE TITLE
message 스택 홈으로 올때 원래 리스트 처음부터 다읽는 문제

### ISSUE THREAD

**Issue by lev-Zero** [lev-Zero/lastpong#158]
홈으로 돌아올경우에 처음부터 다읽어서 안읽은 메세지가 숫자가 엄청 많이 카운트 되는 문제 발견

**Comment by yoopark** [comment]
https://github.com/lev-Zero/lastpong/commit/e4c8f8d91e5f4f8297b0428068918f6f1e945300 로 임시로 해결. 
하지만 새로고침해서 새로 connection 만들어지면 기존 읽었던 알림이 다시 표시되는 문제가 여전히 있습니다. 
이건 근본적으로 읽었는지 안 읽었는지를 서버에 보내야 하는 해결할 수 있는 문제라 너무 헤비해져서 일단은 해당 문제는 남겨두었습니다.
