### ISSUE TITLE
Block 수정예정

### ISSUE THREAD

**Issue by lev-Zero** [lev-Zero/lastpong#162]
Block 기능은 채팅방 안에서만 작동하고 
 프론트 엔드에서 컨트롤해서 
 내가 블락한 유저의 메세지는   msgList mapping과정에서 skip 하도록 하기

**Comment by yoopark** [comment]
https://github.com/lev-Zero/lastpong/commit/8f9d1d5e8aa38551b3120311ac3359d0157883da 로 해결
