### ISSUE TITLE
otpStatus true/false 기준이 뭔가요? 

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#51]
https://github.com/lev-Zero/lastpong/blob/60bab126e83af9184f94197bbe6b0a244d095f19/backend/src/auth/service/auth42.service.ts#L80-L113

otpStatus가 현재 유저의 otp가 on/off 인지 보는 거라고 생각했는데, otpOn== true 이면 otpStatus = false라고 하는게 정반대로 써져 있는 것 같아서, 일단 true/false를 바꾸고 마저 개발하겠습니다!

**Comment by yoopark** [comment]
otp off한 상태로 그냥 42 인증만 하고 날아온 accessToken으로 /user/me를 찍으니까 `400 OTP가 유효하지 않다`는 에러가 뜨네요

**Comment by yoopark** [comment]
코드를 계속 보니까, optOn이랑 otpStatus랑 다른 것 같네요. 
otpStatus는 otp 인증을 성공적으로 마쳤는지 여부인 것 같고, 
otpOn은 otp 기능이 꺼져있는지/켜져있는지 여부인 것 같습니다. 

위에서 바꿔놓았던 true/false는 다시 돌려놓았습니다! 
그런데 user를 부를 때 otpOn true/false도 보내주셔야 할 것 같습니다.
아니면 otpOn을 확인할 수 있는 API를 만들어야 할 것 같아요!

**Comment by yoopark** [comment]
"login success" 주시는게 JSON으로 읽을 수가 없어서 JSON.stringify({'status': 'otpOff'})로 수정했습니다!

**Comment by toy-k** [comment]
이해하신 내용이 맞습니다. 

otpStatus와 auth42Status는 
유저 로그인 상태 확인 플래그로써 
jwt token 생성 위한 Payload에 속한 타입 사용중 입니다. 
(backend/src/auth/interface/payload.interface.ts)

otpOn은 auth42 entity의 colume이면서 
유저가 otp 기능을 on/off했는지 확인할 수 있는 플래그로 사용중입니다.

**Comment by yoopark** [comment]
#61 만 해결되면 이슈 해결
