### ISSUE TITLE
socket.io 공부하기

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#64]
- WebServer 클라이언트가 했던거 생각하면 사실상 Server에 비하면 하는 거 없을 수도?? 코드 돌리는 방법만 눈에 익혀두는 게 우선
- 현재 CORS 문제 해소를 위해 localhost:3000을 proxy로 이용하고 있어서 socket 보내고 받을 때 다른 추가 설정이 필요할 수도 있다 (@sunbchoi)
- `socket.io-client`를 깔면 됨. **감사한 점은 사용하는 함수가 socket.on(데이터 들어오는거 대기상태) / socket.emit(데이터 보내기) 두개밖에 없다는 점이다. 그래서 아마... React라고 또 다르고 Next라고 또 다르고 그런건 거의 없을 듯 하다**

### [웹소켓 이해하기](https://www.peterkimzz.com/websocket-vs-socket-io/)
- 웹소켓 = ws : 표준 / 주식 실시간 주가 처럼 유저 구분 없이 브로드캐스팅할 때 Good
- socket.io : 웹소켓 기술을 더 편하게 만든 라이브러리 / room 기능이 있기 때문에 transcendecne 같은 프로젝트에 매우 적합

### [socket.on과 socket.emit 이해하기](https://socket.io/docs/v4/#:~:text=here%27s%20the%20same%20example%20with%20Socket.IO%3A)
- socket.on과 socket.emit 모두 첫번째 인자로 string을 필요로 하는데, 이게 바로 **이벤트명**이다. 
- 이벤트명 예시 : [lastpong chat API](https://secret-jackal-406.notion.site/chat-API-8317d81f5ee64af08d875394e6d2512a)에 나오는 함수명이 다 이벤트명이다. 
- (Q. room 구분은 socket 연결하는 path에 차이를 두는건가??) A. YES. 아래 적은 Namespace, room 보시길
- **socket.on과 socket.emit하는 양쪽의 이벤트명이 동일해야 한다는 것이 키포인트.** 즉, socket.emit('createChatRoomDm', ...)으로 클라이언트에서 보낸 정보는 socket.on('createChatRoomDm', ...)으로 서버에서 함수를 제작해줘야만 받을 수 있다. webserv는 Request라면 일단 다 받았지만 얘는 이벤트명이 서로 동일해야 한다. 

### [Namespace와 Room](https://inpa.tistory.com/entry/SOCKET-%F0%9F%93%9A-Namespace-Room-%EA%B8%B0%EB%8A%A5)
- Namespace(chat, game 등) >> Room(채팅방 1, 게임방 1 등) >> Socket(각 connection) 포함관계. 
- Namespace, Room을 나누는건 사실 서버에게만 해당. 프론트는 관계 없음. 
- 예를 들면, localhost:3000/chat 으로 소켓을 연결하면 chat Namespace 안에서 관리되는 거고 그런 느낌... 
- Q. room도 path로 접근하는 건가? 예를 들어 localhost:3000/chat/id/1 이런 식으로 connect를 하면 room 1에 자동으로 들어가나? A. 그게 아니라 socket.on/emit의 추가 인자로 주고 받는다
- Q. 프론트에서는 chatRoom 하나 들어가면, join 이벤트로 emit 하고 localhost:3000/chat/1 이런 주소로 새로운 소켓을 만드는건가?  A. 아니다. 소켓은 /chat Namespace에서 하나다

### [Lastpong Chat API](https://secret-jackal-406.notion.site/chat-API-8317d81f5ee64af08d875394e6d2512a) 공부하기

**일단 Mute, Ban 등은 제외하고 핵심 로직부터 짜겠습니다.**

1. 일반 채팅방 플로우
- client1 -> emit createChatRoom
- client1 -> on message?? (Q. 이렇게 listen하는거 맞나요? A. Yes)
- client2 -> emit chatRoomAll(전체 채팅방 목록 띄우기)
- client2 -> (클릭하면) emit chatRoomById (필요 없을 듯. chatRoomAll할 때 이미 id를 주니까)
- client2 -> emit join(path가 아닌 socket.emit의 추가 인자로 roomId를 넣는다, join할 때 그 방에 있는 유저 목록도 함께 불러옴)
- client2 -> on message
- client2 -> emit message

2. DM 플로우
Q. 아직 아무랑도 DM 안한 초기 상태에 이미 전체 친구에 대해 미리 각각 join 해놓아야 되나요?
A. **DM은 createChatRoomDm 내부 로직에 나와 상대 유저가 join하는 기능도 함께 포함되어있습니다.**
- client1 -> client2에게 DM을 보내려고 창을 켠 순간, 만약 이전에 만들어졌던 방 id가 없다면 createChatRoomDm, 있으면 그냥 진행
- createChatRoomDm에서는 나와 상대 유저를 자동으로 join한다. (따로 join 함수가 없음)
- client1, 2는 원래 on directMessage를 이미 한 상태임
- client1 -> emit directMessage
- client2 -> DM 아직 안보냈기 때문에 반응 없음
- client1 -> emit directMessage
- client2 -> 문자가 왔지만 클릭하지 않아서 알림으로 뜸 (이건 프론트에서 알아서 처리해야 할듯. 일단 내용까지 다 이미 온 것임)

> - directMessage(on, emit)
    - [[this.server.to](http://this.server.to/)](http://this.server.to/)([[chatRoomDm.name](http://chatroom.name/)](http://chatroom.name/)).emit('message', {message:data.message,  user: { id: [[user.id](http://user.id/)](http://user.id/), username: user.username } })

**Comment by yoopark** [comment]
지금까지 공부하고 있는 내용인데 한번 틀린게 있는지 봐주시길 바랍니다! 

Q. room도 path로 접근하는 건가? 예를 들어 localhost:3000/chat/id/1 이런 식으로 connect를 하면 room 1에 자동으로 들어가나?
Q. 프론트에서는 chatRoom 하나 들어가면, join 이벤트로 emit 하고 localhost:3000/chat/1 이런 주소로 새로운 소켓을 만드는건가?

이거 두개 혹시 알려주실 수 있나요..? @toy-k

**Comment by yoopark** [comment]
제가 추가로 공부하면서 한번 답해봤습니당..

**Comment by toy-k** [comment]
전반적으로 공부하신내용에 대해 동의합니다.

"1. 일반 채팅방 플로우" 부분에서 client1은 방을 만들고, client2처럼 join도 따로 해야됍니다.
"2.DM 플로우"는 이미 슬랙에서 말씀드린대로 진행하면 될것같습니다. 다만 코드 보면서 더 간단한 방식 떠오르면 공유하겠습니다.

Q-1. room 자체에 접근 하는 방법은 모르겠습니다. 서버쪽에서는 특정 방으로 메시지를 전달하는것과, 특정 소켓(유저)가 속한 방목록 두가지 데이터를 사용하고 있습니다.

Q-2. 제 상상으로는 아래와 같습니다. room 이라는 그룹을 만들고, 그 그룹안에 join한 유저가 포함되는 것으로 상상하고 있습니다. 방 자체가 소켓이 되는건 아니고, 소켓은 항상 연결한 브라우저(유저)로 알고 있습니다. 

![image](https://user-images.githubusercontent.com/88143547/209805190-985f46e7-26a2-47dc-98d5-5a42efc8b787.png)

**Comment by toy-k** [comment]
학습속도가 무지 빠르셔서 부럽네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by yoopark** [comment]
답변 바탕으로 DM 플로우 수정하였습니다 ㅎㅎ 공부는 재밌었는데 로직 만들기 시작하기가 너무 귀찮군요. 밤에 하겠습니다 하하

**Comment by toy-k** [comment]
DM쪽 로직 이건 어떨까요 ?
유저1 -> socket.emit('createChatRoomDM) -> join(user1), join(user2)
유저2 -> socket.on('join') -> 유저1이 블락유저인지 아닌지 확인 -> 블락유저이면 유저2가 socket.emit('leaveDmBlock') 즉시실행해서 방 나감. 나갈때 메시지로 원래 있던방에 "DM보낸 사람은 차단되었습니다"라고 던지고 방나오기.    유저1은 뻘쭘하게 혼자 방에 남아있겠지만, 평가때 자연스럽게 그 창 닫아서 나오게 만들기(socket.emit('leaveDm'))
*leaveDmBlock는 현재 없지만, 만들까 생각중입니다. 

유저2-> 블락유저 아니면 일반채팅룸처럼 소통, 알림은 아까 말씀드린것처럼 socket.on('directmessage') 

이런 방향 어떨까요 ?

**Comment by toy-k** [comment]
- leave(chatRoom) 경우 작동방식입니다.

클라이언트에서 받는 바디에 targetUserId 를 받게 돼요. 
 
아래는 설명은 이런 구조 입니다.


"본인의 leave 요청 -> targetUser ->  행동"

owner -> owner  -> 방삭제
owner -> admin -> 실패 (admin을 일반유저로 만들고 다시 leave 하면 강퇴가능)
owner -> user -> 강퇴

admin -> owner -> 실패
admin -> 다른 admin -> 실패 (admin을 일반유저로 만들 수 없음)
admin -> admin(본인) -> admin 방나감
admin -> user -> 강퇴

user -> owner -> 실패
user -> admin -> 실패
user -> 다른 user -> 실패
user -> user(본인) -> user 방 나감


- DM의 leaveDm은 누군가 강퇴기능없이 스스로 방을 나가는 기능만 두는건 어떨가 싶어요.
다만 디엠보낸 유저가 방을 나가면 방이 삭제되고 기존유저도 방이 나가지고, 
디엠받은 유저가 나가면 방에는 디엠보낸 유저만 남고, 
평가중이라면 자연스럽게 남은 한명이 가진 채팅방을 닫음으로써 
남은 유저는 서버로 leaveDm을 보내게 되고 방이 지워지는 상황으로 일단 구현해보는게 어떨까 싶어요.

**Comment by toy-k** [comment]
https://github.com/users/lev-Zero/projects/1/views/2?layout=board
에서 "[BE] chatRoom, chatRoomDm 'leave, leaveDm' 작동방식"
확인 해주세요
