### ISSUE TITLE
42 API로 로그인했을 때 이 사람이 처음 가입한 사람인지 아닌지 구분하는 방법이 무엇인가요? 

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#74]
현재 42 API를 사용하여 로그인을 하고 로그아웃을 한 뒤 다시 로그인을 눌러도 (otpOn == false이면) 무조건 이름을 새로 입력하는 창으로 이동하도록 라우팅을 짜놨습니다. 이름을 입력한 적 있는 유저인지 구분하고 싶었으나 초기 username이 intra ID로 설정되어 있어 이 사람이 실제 자신의 닉네임을 Intra ID와 똑같이 입력했다면 구분할 방법이 없는 것 같습니다. 

혹시 42 API로 로그인한 뒤에 이 사람이 받은 쿠키만으로 이 사람이 예전에 가입하여 자신의 닉네임을 정한 유저인지 아닌지 구분할 수 있는 방법이 있나요??

**Comment by yoopark** [comment]
otpOn 상태를 바꾸고 재로그인하면 otp 창으로 정상적으로 라우팅 되는 것으로 보아 정보가 사라지는 것은 아닌 것 같네요. 구분 방법만 알려주시면 감사하겠습니다!

**Comment by toy-k** [comment]
![image](https://user-images.githubusercontent.com/88143547/209915066-895d9268-9ffa-43f1-9d96-17b77d1b4845.png)

- 만약 유저가 처음 로그인하면(회원가입) 42api에서 username을 받아오고
그 정보로 username42가 있는지 확인합니다. 
당연히 없을테니,
받아온 username 정보를 user entity 의 username, username42에 할당합니다.
그 이후 프론트에서 유저 이름을 수정하면 user entity의 username이 수정됍니다. 


- 이후 같은 유저가 로그인하면(재로그인) 42api에서 username을 받아오고 
그 정보로 username42가 있는지 확인합니다. 이전에 가입한 이력이 있었다면 해당 유저는 존재하게 되고, 그 유저를 새로 생성하지 않고 토큰 생성 및 발급 및 클라이언트에 전달 후 해당 기능은 마무리 됍니다.

**Comment by yoopark** [comment]
아 /user/me를 했을 때 이제 username42도 온다는거군요
근데 같은지 확인하는 거면, username을 username42와 똑같이 설정하면 문제가 발생하는 거 아닌가요?

**Comment by yoopark** [comment]
제 생각에는, username42 주시는건 유지하고, 
username의 기본값을 username42가 아니라 빈 스트링으로 주시면 어떨까 싶습니다. 
빈 스트링은 애초에 제출이 불가능하기 때문에 /user/me를 했을 때 빈 스트링이라면 처음 가입한 유저로 판단하여 이름 설정 페이지로 넘기겠습니다.

**Comment by toy-k** [comment]
그러면 맨처음에 유저 로그인(회원가입) 인 경우, username을 null로 할당하면 좋겠군요.
코드 수정했습니다

**Comment by yoopark** [comment]
#79 로 해결. 

username 초기값을 null -> '' 로 수정하였습니다!!
