### ISSUE TITLE
localhost 외의 주소로 배포되었을 때 서버가 여전히 localhost:3000이라서 이동을 못하는 버그

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#92]
상대방 컴퓨터로 들어가서 테스트해보려 했는데, 
상대방 컴퓨터 ip는 localhost가 아니라서 localhost:3000/auth 로 이동하면 404 에러가 뜹니다. 
수정 필요

**Comment by toy-k** [comment]
@choi-sunbin 평가중 보고 오셨다는 방법 어떻게 하면 구현가능 한지 알려주세요

**Comment by yoopark** [comment]
물론 프론트엔드에서 SERVER_URL을 전역변수 느낌으로 관리하고 있어서, 그것만 해당 컴퓨터 ip 로 바꿔주면 해결됩니다

**Comment by yoopark** [comment]
일단 SERVER_URL 전역변수 하나만 수정하면 다 바뀌는 식으로 코드를 작성하도록 하겠습니다.

**Comment by yoopark** [comment]
42 callback api 허용 주소를 받아서 다시 시도해봐야 합니다.

**Comment by yoopark** [comment]
https://github.com/lev-Zero/lastpong/commit/322c93cdc9879c96518eebb10c04f47bd4e25f2e 에 다른 주소로 배포시 주의사항을 적어두었습니다. 해결되었습니다.
